### ISSUE TITLE
Json wrongly wrote

### ISSUE THREAD

**Issue by NT-me** [5hirish/tweet_scrapper#16]
Hi !
Your package is very very cool !
I used an other tweet scrapper who was very slooooow. But your's is perfect except on windows he failed when need to write json or csv file.
Because when i try too load the json this error message sawn :

```
Traceback (most recent call last):
  File "main.py", line 40, in buttonClicked
    a = mainCol.gen_mainCol()
  File "C:\Users\U\Documents\ActualiT\mainCol.py", line 231, in gen_mainCol
    all_parse()
  File "C:\Users\U\Documents\ActualiT\mainCol.py", line 119, in all_parse
    articleTWEET = parse(PATH_FileTWEET)
  File "C:\Users\U\Documents\ActualiT\mainCol.py", line 16, in parse
    article = json.loads(File.read())
  File "C:\Users\U\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\U\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\U\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 20715 (char 20714)

```

And i call the package here ->
https://github.com/gnouf1/ActualiT/blob/master/twitter.py

This error exist only on windows not on Linux (tested with Xubuntu)

**Comment by NT-me** [comment]
Okay I found,
Multi-threading error from me
